version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: patients
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
  
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mongo
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/patients
      - MONGO_URL=mongodb://mongo:27017
